server:
  port: 8081
  tomcat:
    max-http-form-post-size: 10000000
  servlet:
    context-path: /questionary

spring:
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher # swagger需要的配置
  datasource:
    username: root
    password: Root123.
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/questionary?characterEncoding=utf-8

mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl